# Generated by Django 5.0 on 2025-11-26 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIncidencia',
            fields=[
                ('id_tipo_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ej: Incapacidad, Permiso con goce, Comisión sindical', max_length=200, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_incidencia_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_incidencia_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Tipo de Incidencia',
                'verbose_name_plural': 'Tipos de Incidencias',
                'db_table': 'tipo_incidencia',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('autorizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Autorizada por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='trabajadores.trabajador', verbose_name='Trabajador')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('id_tipo_incidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='incidencias.tipoincidencia', verbose_name='Tipo de Incidencia')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencia',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
