# Generated by Django 5.0 on 2025-12-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidencia',
            options={'ordering': ['-fecha_inicio', '-created_at'], 'verbose_name': 'Incidencia', 'verbose_name_plural': 'Incidencias'},
        ),
        migrations.AddField(
            model_name='incidencia',
            name='comentario_autorizacion',
            field=models.TextField(blank=True, verbose_name='Comentario de Autorización'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Autorización'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autorización'),
        ),
        migrations.AddField(
            model_name='tipoincidencia',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='tipoincidencia',
            name='requiere_autorizacion',
            field=models.BooleanField(default=True, help_text='Define si este tipo de incidencia requiere autorización de un superior', verbose_name='Requiere Autorización'),
        ),
    ]
