# Generated by Django 5.0 on 2025-11-26 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioLaboral',
            fields=[
                ('id_calendario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('es_inhabil', models.BooleanField(default=False, verbose_name='¿Es día inhábil?')),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Día festivo, Vacaciones, etc.', max_length=200, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendarios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendarios_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Día del Calendario Laboral',
                'verbose_name_plural': 'Calendario Laboral',
                'db_table': 'calendario_laboral',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='JornadaLaboral',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ej: Jornada Matutina, Jornada Vespertina', max_length=200, verbose_name='Descripción')),
                ('hora_entrada', models.TimeField(verbose_name='Hora de Entrada')),
                ('hora_salida', models.TimeField(verbose_name='Hora de Salida')),
                ('dias_semana', models.CharField(help_text='Ej: L-V, L-S, o 1,2,3,4,5', max_length=20, verbose_name='Días de la Semana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Jornada Laboral',
                'verbose_name_plural': 'Jornadas Laborales',
                'db_table': 'jornada_laboral',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TrabajadorJornada',
            fields=[
                ('id_trabajador_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar vacío si es vigente actualmente', null=True, verbose_name='Fecha de Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajador_jornadas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('id_jornada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores_asignados', to='jornadas_laborales.jornadalaboral', verbose_name='Jornada Laboral')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas_asignadas', to='trabajadores.trabajador', verbose_name='Trabajador')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajador_jornadas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Asignación de Jornada',
                'verbose_name_plural': 'Asignaciones de Jornadas',
                'db_table': 'trabajador_jornada',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('id_trabajador', 'fecha_inicio')},
            },
        ),
    ]
