# Generated by Django 5.0 on 2025-12-02 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas_laborales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornadalaboral',
            name='dias_semana',
        ),
        migrations.AlterField(
            model_name='jornadalaboral',
            name='descripcion',
            field=models.CharField(choices=[('MAT', 'Jornada Matutina'), ('VES', 'Jornada Vespertina'), ('NOC', 'Jornada Nocturna'), ('COM', 'Jornada Completa'), ('MED', 'Media Jornada'), ('INT', 'Jornada Intermitente'), ('ESP', 'Jornada Especial')], help_text='Seleccione el tipo de jornada laboral', max_length=3, verbose_name='Tipo de Jornada'),
        ),
        migrations.CreateModel(
            name='JornadaDias',
            fields=[
                ('id_jornada_dia', models.AutoField(primary_key=True, serialize=False)),
                ('numero_dia', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Día de la Semana')),
                ('id_jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='jornadas_laborales.jornadalaboral', verbose_name='Jornada Laboral')),
            ],
            options={
                'verbose_name': 'Día de Jornada',
                'verbose_name_plural': 'Días de Jornadas',
                'db_table': 'jornada_dias',
                'ordering': ['numero_dia'],
                'unique_together': {('id_jornada', 'numero_dia')},
            },
        ),
    ]
