# Generated by Django 5.0 on 2025-12-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador del Sistema'), ('jefe', 'Jefe de Área/Supervisor'), ('trabajador', 'Trabajador'), ('espera', 'en espera')], default='espera', max_length=50, verbose_name='Rol'),
        ),
    ]
