# Generated by Django 5.0 on 2025-11-26 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_puesto', models.CharField(max_length=200, verbose_name='Nombre del Puesto')),
                ('nivel', models.CharField(help_text='Ej: Académico, Administrativo, Directivo', max_length=100, verbose_name='Nivel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puestos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puestos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'db_table': 'puesto',
                'ordering': ['nombre_puesto'],
            },
        ),
        migrations.CreateModel(
            name='TipoNombramiento',
            fields=[
                ('id_tipo_nombramiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ej: Base, Confianza, Interino', max_length=150, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_nombramiento_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_nombramiento_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Tipo de Nombramiento',
                'verbose_name_plural': 'Tipos de Nombramiento',
                'db_table': 'tipo_nombramiento',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('numero_empleado', models.CharField(max_length=20, unique=True, verbose_name='Número de Empleado')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=150, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=150, verbose_name='Apellido Materno')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('curp', models.CharField(max_length=18, verbose_name='CURP')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('id_puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='trabajadores.puesto', verbose_name='Puesto')),
                ('id_tipo_nombramiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='trabajadores.tiponombramiento', verbose_name='Tipo de Nombramiento')),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='unidades.unidadadministrativa', verbose_name='Unidad Administrativa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'trabajador',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
    ]
