# Generated by Django 5.0 on 2025-12-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='estatus',
            field=models.CharField(choices=[('ASI', 'Asistencia Normal'), ('RET', 'Retardo'), ('FAL', 'Falta'), ('JUS', 'Falta Justificada')], default='FAL', max_length=3, verbose_name='Estatus'),
        ),
    ]
